import './globals.css';
import Configure from './Configure';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Configure>{children}</Configure>
      </body>
    </html>
  );
}
