name: CICD Backoffice Staging

on:
  push:
    branches:
      - staging

jobs:
  build_push_deploy:
    name: Build -> Push -> Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on Development
        uses: appleboy/ssh-action@master
        env:
          IMAGE_NAME: ${{ secrets.IMAGE_NAME_STAGING }}
          IMAGE_TAG: ${{ secrets.IMAGE_TAG_STAGING }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          envs: IMAGE_NAME,IMAGE_TAG
          script: |
            echo "IMAGE: $IMAGE_NAME:$IMAGE_TAG"
            cd greenskill-education-backoffice
            git config --global user.email "bismika@amati.com"
            git config --global user.name "Bismika Amati"
            git fetch
            git pull origin staging --no-rebase
            # sudo docker stop $IMAGE_NAME
            # sudo docker rm $IMAGE_NAME
            # sudo docker rmi $IMAGE_NAME:$IMAGE_TAG
            sudo docker system prune
            y
            sudo docker build --no-cache --build-arg NEXT_PUBLIC_BASE_URL="http://34.128.92.185:4001" --build-arg NEXT_PUBLIC_API="http://34.128.92.185:3000/api" -t $IMAGE_NAME:$IMAGE_TAG -f Dockerfile .
            sudo docker run --name $IMAGE_NAME -p 4001:4000 -d $IMAGE_NAME:$IMAGE_TAG
